# Internal Traefik for PullPreview previews.

global:
    checkNewVersion: false
    sendAnonymousUsage: false

log:
    level: INFO

accessLog:
    format: json
    fields:
        defaultMode: keep
        names:
            ClientUsername: drop
        headers:
            defaultMode: drop
            names:
                User-Agent: keep
                Content-Type: keep
                X-Request-Id: keep

ping:
    entryPoint: web

entryPoints:
    web:
        address: ':80'

providers:
    file:
        filename: /etc/traefik/dynamic.yml
