[[alerter]]
name = "discord"
description = "Discord alerts for Reputo Komodo resources."
tags = ["reputo", "alerts"]

[alerter.config]
enabled = true

[alerter.config.endpoint]
type = "Discord"

[alerter.config.endpoint.params]
url = "[[KOMODO_DISCORD_WEBHOOK_URL]]"
