global:
    checkNewVersion: false
    sendAnonymousUsage: false

log:
    level: DEBUG

accessLog:
    format: json
    fields:
        defaultMode: keep
        names:
            ClientUsername: drop
        headers:
            defaultMode: drop
            names:
                User-Agent: keep
                Content-Type: keep
                X-Request-Id: keep

api: { dashboard: true, insecure: false }
ping:
    entryPoint: web

entryPoints:
    web:
        address: ':80'
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https
    websecure:
        address: ':443'

certificatesResolvers:
    cloudflare:
        acme:
            email: 'info@reputo.org'
            storage: /var/traefik/certs/cloudflare-acme.json
            caServer: 'https://acme-v02.api.letsencrypt.org/directory'
            dnsChallenge:
                provider: cloudflare
                resolvers:
                    - '1.1.1.1:53'
                    - '8.8.8.8:53'

providers:
    docker:
        exposedByDefault: false
        network: production
