name: Pull Preview

on:
    pull_request:
        branches: [main]
        types: [labeled, unlabeled, closed]

concurrency: preview-lifecycle-${{ github.event.pull_request.number }}

permissions:
    contents: read

jobs:
    build:
        if: |
            github.event.action == 'labeled' &&
            github.event.label.name == 'pullpreview'
        permissions:
            contents: read
            packages: write
        uses: ./.github/workflows/_build-and-push.yml
        with:
            ref: ${{ github.event.pull_request.head.sha }}
            push: true
            affected: false

    preview:
        needs: build
        permissions:
            contents: read
            pull-requests: write
            statuses: write
        if: |
            !cancelled() &&
            (needs.build.result == 'success' || needs.build.result == 'skipped') &&
            (github.event.label.name == 'pullpreview' ||
             (github.event.action == 'closed' &&
              contains(github.event.pull_request.labels.*.name, 'pullpreview')))
        uses: ./.github/workflows/_pull-preview.yml
        with:
            ref: ${{ github.event.pull_request.head.sha }}
            deployment: ${{ github.event.action == 'labeled' }}
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            DEEPFUNDING_API_KEY: ${{ secrets.DEEPFUNDING_API_KEY }}
            ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
            BLOCKFROST_API_KEY: ${{ secrets.BLOCKFROST_API_KEY }}
            DEEP_ID_CLIENT_ID: ${{ secrets.DEEP_ID_CLIENT_ID }}
            DEEP_ID_CLIENT_SECRET: ${{ secrets.DEEP_ID_CLIENT_SECRET }}
